### ISSUE TITLE
Question about Repeat element STAR index

### ISSUE THREAD

**Issue by Shashankti** [YeoLab/eclip#36]
Hello,

I have been trying to analyse some eCLIP-Seq data and I am following this pipeline. I have some issue with the STAR rmRep step. Since I do not have access to the RepBase data, I decided to use msRepDB, which is an alternative to RepBase.
[msRepDB](https://msrepdb.cbrc.kaust.edu.sa/pages/msRepDB/index.html).
I have the fasta file which contains the repetitive elements however I am unable to generate index using STAR. Could you please suggest a way to use the fasta file for alignment using STAR. I am also attaching the fasta file for your reference(as a .txt file)
[9606.txt](https://github.com/YeoLab/eCLIP/files/10425767/9606.txt)

Thanks,
Shashank

**Comment by byee4** [comment]
Hi Shashank, I was able to generate the genome index with these parameters, with STAR 2.7.6a:

STAR \
--runThreadN 8 \
--runMode genomeGenerate \
--genomeDir repbase_STARindex \
--genomeFastaFiles 9606.fasta \
--genomeSAindexNbases 9


SECURE: MESSAGE FROM Shashankti ON 1/16/23, 4:44 AM


Hello,

I have been trying to analyse some eCLIP-Seq data and I am following this pipeline. I have some issue with the STAR rmRep step. Since I do not have access to the RepBase data, I decided to use msRepDB, which is an alternative to RepBase.
msRepDB<https://urldefense.com/v3/__https:/msrepdb.cbrc.kaust.edu.sa/pages/msRepDB/index.html__;!!LLK065n_VXAQ!mL6ak19sIRW0-mAFkGvksUHNJ0eGLiXxR5EnZmiqzm8F6aQE4tS08gRZdMZYUGXdCuMUVzZFx8f7r285C0U9dn7cRhkg$>.
I have the fasta file which contains the repetitive elements however I am unable to generate index using STAR. Could you please suggest a way to use the fasta file for alignment using STAR. I am also attaching the fasta file for your reference(as a .txt file)
9606.txt<https://urldefense.com/v3/__https:/github.com/YeoLab/eCLIP/files/10425767/9606.txt__;!!LLK065n_VXAQ!mL6ak19sIRW0-mAFkGvksUHNJ0eGLiXxR5EnZmiqzm8F6aQE4tS08gRZdMZYUGXdCuMUVzZFx8f7r285C0U9dt8snPOs$>

Thanks,
Shashank

**Comment by Shashankti** [comment]
Hello again,

Thank you so much for your response, I was able to generate STAR index using your commands. The issue occurred because earlier I was trying to use the GTF file (Homo_sapiens.GRCh38.108.gtf) for generating the index with the fasta file. Thanks for the help
