### ISSUE TITLE
Problem in 'Input normalzation'

### ISSUE THREAD

**Issue by dahun73** [YeoLab/eclip#8]
Hello.

I have problems and some questions for eCLIP-seq data analyzing.

Now I'm trying to input normalization after Clipper peak calling, but error message came out like this:
![image](https://user-images.githubusercontent.com/52641420/84117967-4a202800-aa6d-11ea-9662-1eb5ffdc2814.png)
Use of uninitialized value $strand in concatenation (.) or string at /usr/bin/overlap_peakfi_with_bam_PE.pl line 401, <B> line 208867.
R1 strand error 83

I don't understand exactly about R1 strand error.
Actually, I tried to start at Clipper stage. Maybe I think the BAM files were not made well.
Would you tell me what I should do?

Because eCLIP pipelines was made by python or perl scripts, it is hard to fit this environment and input file format.

How can I try this whole process without using script? just using linux shell command each step.

Thank you.

**Comment by byee4** [comment]
This appears to be the paired-end protocol? The error that I'm seeing is that input normalization is finding read1 which should have been filtered prior to Clipper. This is done because it is read2 that is enriched for termination at the crosslinked site. In pipeline-terms this step corresponds to [samtools-viewr2.cwl](https://github.com/YeoLab/eclip/blob/master/cwl/samtools-viewr2.cwl), however if you are running commands separately, this step should be run prior to Clipper and input-normalization:

```
samtools view \
-f 128 \
-b \
-o EXAMPLE_PE.rep2_clip.C01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.bam \
EXAMPLE_PE.rep2_clip.C01.r1.fq.genome-mappedSo.rmDupSo.merged.bam
```
